version: 1

labels:
  - label: "documentation"
    files:
      - "**/*.md"
      - "README*"
      - "docs/**"

  - label: "config"
    files:
      - ".github/**"
      - "*.yml"
      - "*.yaml"

  - label: "frontend"
    files:
      - "app/**"
      - "components/**"
      - "public/**"

  - label: "dependencies"
    files:
      - "package.json"
      - "package-lock.json"
      - ".nvmrc"

  - label: "ci"
    files:
      - ".github/workflows/**"
      - ".github/dependabot.yml"

  - label: "styles"
    files:
      - "**/*.css"
      - "**/*.scss"
